name: Code Scans with SFDX Scanner

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - integration
    paths:
      - "force-app/**"

jobs:
  sfdx-scanner:
    name: "Validate Code"
    uses: "alexandrafanevich/devops-center-actions/.github/workflows/validate-code.yml@main"
    secrets: inherit
